apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: klusteradep
  name: klusterapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klusterapp
  strategy: {}
  template:
    metadata:
      labels:
        app: klusterapp
    spec:
      containers:
      - image: khatanve/webapp-demo
        name: klusterapp
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: klusterapp-svc
spec:
  type: NodePort
  selector:
    app: klusterapp
  ports:
  - port: 80
    targetPort: 8080
    #nodePort: 30083
  