image:
  repository: CHANGE_ME.dkr.ecr.eu-central-1.amazonaws.com/demo-app
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  host: ""
